# services section defines the applications that Docker Compose should manage.
services:
  postgres:
    image: postgres:16.14-alpine
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

    networks:
      - evidencevault_network

  qdrant:
    image: qdrant/qdrant:v1.18.2
    restart: unless-stopped

    ports:
      - "${QDRANT_HTTP_PORT}:6333"
      - "${QDRANT_GRPC_PORT}:6334"

    volumes:
      - qdrant_data:/qdrant/storage

    networks:
      - evidencevault_network

volumes:
  postgres_data:
  qdrant_data:

networks:
  evidencevault_network:
    driver: bridge